export const Routers = [
  {
    url: './Page/Home/index',
    tag: 'Home',
    name: '',
    parent: false,
    child: false,
    model: true,
    parentId: '',
    id: 1,
    icon: 'star',
  },
  {
    url: './Page/Buy/index',
    name: 'Buy',
    tag: 'Buy',
    parent: false,
    child: false,
    model: true,
    parentId: 1,
    id: 2,
    icon: 'star',
  },
  {
    url: './Page/About/index',
    name: 'About',
    tag: 'About',
    parent: false,
    child: false,
    model: true,
    parentId: 1,
    id: 3,
    icon: 'star',
  },
];
