POST http://localhost:5000/Tweets/create
Content-Type: application/json

{
    "TweetText":"Random Thing in Twitter Number 4",
    "user":"62332312c0aacaf1d432353d",
    "username":"test"
}

###

GET http://localhost:5000/Tweets/Train Heartent

###

POST http://localhost:5000/Tweets/all
Content-Type: application/json

{}

###

DELETE  http://localhost:5000/Tweets/delete
Content-Type: application/json

{
    "id":"622238e69fb0514aa6fb6341"
}
###################################################

POST http://localhost:5000/Profile/create
Content-Type: application/json

{
    "username":"Ahmed" , 
    "Avatar":"Ahmed Avtar usser" , 
    "RealName":"Ahmed test" ,
    "YourTweets":[],
    "Followers":[],
    "Following":[],
    "NumberOfTweets":[],
    "NumberOfLikedTWeets":[]
}

###

POST http://localhost:5000/Profile/all
Content-Type: application/json

{}
###
GET http://localhost:5000/Profile/Train Heartent

###

PUT http://localhost:5000/Profile/62332312c0aacaf1d432353d
Content-Type: application/json

{
    "username": "test",
      "Avatar": "test Avtar usser",
      "RealName": "test tester",
      "Followers": ["62224083d99964c8fd924274","622282a7d22250bc6720b992"],
      "Following": ["62224083d99964c8fd924274","622282a7d22250bc6720b992"],
      "YourTweets": ["623453cb75a1bd999d45bee2","623453ce75a1bd999d45bee4","623453c675a1bd999d45bee0","623453c375a1bd999d45bede","623453bc75a1bd999d45bedc"],
      "NumberOfLikedTWeets": []
}
################Products##########################

POST http://localhost:5000/products/create
Content-Type: application/json

{
    "name":"mouse" , 
    "img":"https://m.media-amazon.com/images/I/61O-tBIkcfS.jpg" , 
    "price":320 ,
    "stock":24

}

###

POST http://localhost:5000/products/all
Content-Type: application/json

{}
###
DELETE  http://localhost:5000/products/delete
Content-Type: application/json

{
    "id":"6377c095fe51278f440f6d8c"
}


###
POST http://localhost:5000/products/find
Content-Type: application/json

{
    "id":"6377c05efe51278f440f6d87"
}