POST http://localhost:5000/Tweets/create
Content-Type: application/json

{
    "TweetText":"Random Thing in Twitter Number 7",
    "user":"62224083d99964c8fd924274",
    "username":"Train Heartent"
}

###

GET http://localhost:5000/Tweets/Train Heartent

###

POST http://localhost:5000/Tweets/all
Content-Type: application/json

{}

###

DELETE  http://localhost:5000/Tweets/delete
Content-Type: application/json

{
    "id":"622238e69fb0514aa6fb6341"
}
###################################################

POST http://localhost:5000/Profile/create
Content-Type: application/json

{
    "username":"Hataki kakashi" , 
    "Avatar":"Ranom Avtar usser" , 
    "RealName":"Jaffer sinan" ,
    "Followers":[],
    "Following":[],
    "NumberOfTweets":[],
    "NumberOfLikedTWeets":[]
}

###

POST http://localhost:5000/Profile/all
Content-Type: application/json

{}
###
GET http://localhost:5000/Profile/Hataki kakashi